#!/bin/bash
gvm-manage-certs -a

create admin user

gvmd --create-user=admin --password=admin

update feeds

greenbone-certdata-sync

greenbone-scapdata-sync

mkdir iana_service_ports 
cd iana_service_ports 
wget https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xml 
gvm-portnames-update service-names-port-numbers.xml
cd /opt/gvm/src

configure and install gsa

cd gsa 
 export PKG_CONFIG_PATH=/opt/gvm/lib/pkgconfig:$PKG_CONFIG_PATH 
 mkdir build 
 cd build/ 
 cmake -DCMAKE_INSTALL_PREFIX=/opt/gvm .. 
 make 
 make doc 
 make install 
 touch /opt/gvm/var/log/gvm/gsad.log 
 cd /opt/gvm/src

cd /opt/gvm/src 
export PKG_CONFIG_PATH=/opt/gvm/lib/pkgconfig:$PKG_CONFIG_PATH 
virtualenv --python python3.7  /opt/gvm/bin/ospd-scanner/ 
source /opt/gvm/bin/ospd-scanner/bin/activate

mkdir /opt/gvm/var/run/ospd/ 
cd ospd 
pip3 install . 
cd /opt/gvm/src

cd ospd-openvas ;\
pip3 install . ;\
cd /opt/gvm/src
